// Cloudflare Workers types. Generated by `npm run types` but manually maintained for now.

interface Env {
  AI: Ai;
  ASSETS: Fetcher;
  HolstonAgent: DurableObjectNamespace<import("./src/server").HolstonAgent>;
  SKILLS_BUCKET: R2Bucket;
  SKILLS_INDEX: VectorizeIndex;
  LOADER: WorkerLoader;
  BROWSER: import("agents/browser").BrowserBinding;
  TEAM_DOMAIN?: string;
  POLICY_AUD?: string;
  OWNER_EMAIL?: string;
  ALLOWED_EMAIL_SENDERS?: string;
  EMAIL_SIGNING_SECRET?: string;
  EMAIL?: SendEmail;
  VAPID_PUBLIC_KEY?: string;
  VAPID_PRIVATE_KEY?: string;
  VAPID_SUBJECT?: string;
  TELEGRAM_BOT_TOKEN?: string;
  TELEGRAM_BOT_USERNAME?: string;
  TELEGRAM_WEBHOOK_SECRET_TOKEN?: string;
  MCP_SERVER_URL?: string;
  /** Bearer token gating Holston's own MCP server at /mcp (owner secret). */
  MCP_ACCESS_KEY?: string;
  /** For fetching browser session recordings via the REST API (owner secrets). */
  CF_ACCOUNT_ID?: string;
  CF_API_TOKEN?: string;
}
