// Cloudflare Workers types. Generated by `npm run types` but manually maintained for now.

interface Env {
  AI: Ai;
  ASSETS: Fetcher;
  HolstonAgent: DurableObjectNamespace;
  SKILLS_BUCKET: R2Bucket;
  SKILLS_INDEX: VectorizeIndex;
  TEAM_DOMAIN?: string;
  POLICY_AUD?: string;
  TELEGRAM_BOT_TOKEN?: string;
  TELEGRAM_BOT_USERNAME?: string;
  TELEGRAM_WEBHOOK_SECRET_TOKEN?: string;
}